services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./.env
    volumes:
     #host_path:container_path(this is where the standard path for postgres data directory is)
      - ./data:/var/lib/postgresql/data
      #Anything you put in ./init (SQL or .sh files) will run once when the database is empty.
      # official Postgres Docker image checks /docker-entrypoint-initdb.d on container start.
      #If the database is empty, it runs all .sql and .sh files there automatically.
      ##- ./init:/docker-entrypoint-initdb.d
    ports: 
      - '5432:5432'

  redpanda: 
    image: redpandadata/redpanda:v23.2.11
    ports:
    #if you change 9092 inside the container (the right side), Kafka won’t work,
    #because the image is preconfigured to listen on 9092 for clients.
      - '9092:9092'
    #Yes. It ensures your app can connect whether you are running it directly
    #on your machine (for easy debugging) or inside a container (for final testing) without changing the Redpanda configuration.
      - '29092:29092'
    volumes:
      - ./redpanda_data:/var/lib/redpanda/data
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092



  redis: 
    image: redis:8-alpine
    ports:
      #default redis port is 6379
      - '6379:6379'
    volumes:
      - ./redis_data:/data

  reservationWorker:
    image: flash-sale-orchestrater-consumera 
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - ./Consumers:/app      # live hot-reload
      - ./go.mod:/app/go.mod       # Mounts the specific file
      - ./go.sum:/app/go.sum       # Mounts the specific file
    command: go run ./reservationWorker
    deploy:
      replicas: 3


  insertionWorker:
    image: flash-sale-orchestrater-consumerb
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - ./Consumers:/app
      - ./go.mod:/app/go.mod      
      - ./go.sum:/app/go.sum           
    command: go run ./insertionWorker
    deploy:
      replicas: 3

  consumerC:
    image: flash-sale-orchestrater-consumerc
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile  
    volumes:
      - ./Consumers:/app
      - ./go.mod:/app/go.mod     
      - ./go.sum:/app/go.sum      
    command: go run ./consumerC
    deploy:
      replicas: 3

  consumerD:
    image: flash-sale-orchestrater-consumerd
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile   
    volumes:
      - ./Consumers:/app
      - ./go.mod:/app/go.mod       
      - ./go.sum:/app/go.sum           
    command: go run ./consumerD
    deploy:
      replicas: 3

  #----FOR PRODUCTION
  # consumerA:
  #   build:
  #     context: ./Consumers
  #     dockerfile: DockerFile
  #   image: flash-sale-orchestrater-consumera  
  #   command: /app/bin/a 
  #   deploy: {replicas: 3}

  # consumerB:
  #   build:
  #     context: ./Consumers
  #     dockerfile: DockerFile
  #   image: flash-sale-orchestrater-consumerb
  #   command: /app/bin/b 
  #   deploy: {replicas: 3}

  # consumerC:
  #   build:
  #     context: ./Consumers
  #     dockerfile: DockerFile
  #   image: flash-sale-orchestrater-consumerc   
  #   command: /app/bin/c 
  #   deploy: {replicas: 3}

  
  # consumerD:
  #   build:
  #     context: ./Consumers
  #     dockerfile: DockerFile
  #   image: flash-sale-orchestrater-consumerd  
  #   command: /app/bin/d 
  #   deploy: {replicas: 3}
  
networks:
  default:
